package io.goodforgod.aws.lambda.events;

import io.goodforgod.aws.lambda.events.cognito.*;
import io.goodforgod.aws.lambda.events.dynamodb.*;
import io.goodforgod.aws.lambda.events.gateway.*;
import io.goodforgod.aws.lambda.events.kinesis.*;
import io.goodforgod.aws.lambda.events.s3.*;
import io.goodforgod.aws.lambda.events.system.*;
import io.goodforgod.graalvm.hint.annotation.ReflectionHint;

/**
 * @author Anton Kurako (GoodforGod)
 * @since 22.08.2022
 */
@ReflectionHint(
        value = { ReflectionHint.AccessType.ALL_DECLARED },
        types = {
                // cognito
                CognitoEvent.class,
                CognitoEvent.DatasetRecord.class,
                CognitoUserPoolCreateAuthChallengeEvent.class,
                CognitoUserPoolCreateAuthChallengeEvent.ChallengeResult.class,
                CognitoUserPoolCreateAuthChallengeEvent.Request.class,
                CognitoUserPoolCreateAuthChallengeEvent.Response.class,
                CognitoUserPoolCustomMessageEvent.class,
                CognitoUserPoolCustomMessageEvent.Request.class,
                CognitoUserPoolCustomMessageEvent.Response.class,
                CognitoUserPoolDefineAuthChallengeEvent.class,
                CognitoUserPoolDefineAuthChallengeEvent.ChallengeResult.class,
                CognitoUserPoolDefineAuthChallengeEvent.Request.class,
                CognitoUserPoolDefineAuthChallengeEvent.Response.class,
                CognitoUserPoolEvent.class,
                CognitoUserPoolEvent.CallerContext.class,
                CognitoUserPoolEvent.Request.class,
                CognitoUserPoolMigrateUserEvent.class,
                CognitoUserPoolMigrateUserEvent.Request.class,
                CognitoUserPoolMigrateUserEvent.Response.class,
                CognitoUserPoolPostAuthenticationEvent.class,
                CognitoUserPoolPostAuthenticationEvent.Request.class,
                CognitoUserPoolPostConfirmationEvent.class,
                CognitoUserPoolPostConfirmationEvent.Request.class,
                CognitoUserPoolPreAuthenticationEvent.class,
                CognitoUserPoolPreAuthenticationEvent.Request.class,
                CognitoUserPoolPreSignUpEvent.class,
                CognitoUserPoolPreSignUpEvent.Request.class,
                CognitoUserPoolPreSignUpEvent.Response.class,
                CognitoUserPoolPreTokenGenerationEvent.class,
                CognitoUserPoolPreTokenGenerationEvent.Request.class,
                CognitoUserPoolPreTokenGenerationEvent.Response.class,
                CognitoUserPoolPreTokenGenerationEvent.GroupConfiguration.class,
                CognitoUserPoolPreTokenGenerationEvent.ClaimsOverrideDetails.class,
                CognitoUserPoolVerifyAuthChallengeResponseEvent.class,
                CognitoUserPoolVerifyAuthChallengeResponseEvent.Request.class,
                CognitoUserPoolVerifyAuthChallengeResponseEvent.Response.class,

                // dynamodb
                DynamoDBAttributeValue.class,
                DynamoDBEvent.class,
                DynamoDBIdentity.class,
                DynamoDBStreamRecord.class,
                DynamoDBTimeWindowEvent.class,

                // gateway
                APIGatewayCustomAuthorizerEvent.class,
                APIGatewayProxyEvent.class,
                APIGatewayProxyEvent.RequestIdentity.class,
                APIGatewayProxyEvent.ProxyRequestContext.class,
                APIGatewayProxyResponse.class,
                APIGatewayV2CustomAuthorizerEvent.class,
                APIGatewayV2HTTPEvent.class,
                APIGatewayV2HTTPEvent.RequestContext.class,
                APIGatewayV2HTTPEvent.RequestContext.Http.class,
                APIGatewayV2HTTPEvent.RequestContext.IAM.class,
                APIGatewayV2HTTPEvent.RequestContext.CognitoIdentity.class,
                APIGatewayV2HTTPEvent.RequestContext.Authorizer.class,
                APIGatewayV2HTTPEvent.RequestContext.Authorizer.JWT.class,
                APIGatewayV2HTTPResponse.class,
                APIGatewayV2WebSocketEvent.class,
                APIGatewayV2WebSocketEvent.RequestContext.class,
                APIGatewayV2WebSocketEvent.RequestIdentity.class,
                APIGatewayV2WebSocketResponse.class,
                BodyEvent.class,
                Base64BodyEvent.class,

                // kinesis
                KinesisAnalyticsFirehoseInputPreprocessingEvent.class,
                KinesisAnalyticsFirehoseInputPreprocessingEvent.Record.class,
                KinesisAnalyticsInputPreprocessingResponse.class,
                KinesisAnalyticsInputPreprocessingResponse.Record.class,
                KinesisAnalyticsInputPreprocessingResponse.Result.class,
                KinesisAnalyticsOutputDeliveryEvent.class,
                KinesisAnalyticsOutputDeliveryEvent.Record.class,
                KinesisAnalyticsOutputDeliveryResponse.class,
                KinesisAnalyticsOutputDeliveryResponse.Record.class,
                KinesisAnalyticsOutputDeliveryResponse.Result.class,
                KinesisAnalyticsStreamsInputPreprocessingEvent.class,
                KinesisAnalyticsStreamsInputPreprocessingEvent.Record.class,
                KinesisEvent.class,
                KinesisEvent.Record.class,
                KinesisEvent.KinesisEventRecord.class,
                KinesisFirehoseEvent.class,
                KinesisFirehoseEvent.Record.class,
                KinesisTimeWindowEvent.class,

                // s3
                S3BatchEvent.class,
                S3BatchEvent.Job.class,
                S3BatchEvent.Task.class,
                S3BatchResponse.class,
                S3BatchResponse.Result.class,
                S3BatchResponse.ResultCode.class,
                S3Event.class,
                S3EventNotification.class,
                S3EventNotification.S3EventNotificationRecord.class,
                S3EventNotification.RequestParametersEntity.class,
                S3EventNotification.ResponseElementsEntity.class,
                S3EventNotification.S3BucketEntity.class,
                S3EventNotification.S3Entity.class,
                S3EventNotification.S3ObjectEntity.class,
                S3EventNotification.UserIdentityEntity.class,
                S3ObjectLambdaEvent.class,
                S3ObjectLambdaEvent.Configuration.class,
                S3ObjectLambdaEvent.GetObjectContext.class,
                S3ObjectLambdaEvent.UserIdentity.class,
                S3ObjectLambdaEvent.UserRequest.class,

                // system
                CloudFormationCustomResourceEvent.class,
                CloudFrontEvent.class,
                CloudFrontEvent.CF.class,
                CloudFrontEvent.Record.class,
                CloudFrontEvent.Config.class,
                CloudFrontEvent.Request.class,
                CloudFrontEvent.Response.class,
                CloudFrontEvent.Header.class,
                CloudWatchLogsEvent.class,
                CloudWatchLogsEvent.AWSLogs.class,
                CodeCommitEvent.class,
                CodeCommitEvent.CodeCommit.class,
                CodeCommitEvent.Record.class,
                CodeCommitEvent.Reference.class,
                ConfigEvent.class,
                IAMPolicyResponse.class,
                IAMPolicyResponse.PolicyDocument.class,
                IAMPolicyResponse.Statement.class,
                LambdaDestinationEvent.class,
                LambdaDestinationEvent.RequestContext.class,
                LoadBalancerRequest.class,
                LoadBalancerRequest.RequestContext.class,
                LoadBalancerRequest.Elb.class,
                LoadBalancerResponse.class,
                SecretsManagerRotationEvent.class,
                SimpleIAMPolicyResponse.class,

                // common
                ActiveMQEvent.class,
                AppSyncLambdaAuthorizerEvent.class,
                AppSyncLambdaAuthorizerResponse.class,
                ActiveMQEvent.class,
                ActiveMQEvent.class,
                ConfigEvent.class,
                IoTButtonEvent.class,
                KafkaEvent.class,
                KafkaEvent.KafkaEventRecord.class,
                KafkaEvent.TopicPartition.class,
                LexEvent.class,
                LexEvent.Bot.class,
                LexEvent.CurrentIntent.class,
                RabbitMQEvent.class,
                RabbitMQEvent.RabbitMessage.class,
                RabbitMQEvent.BasicProperties.class,
                ScheduledEvent.class,
                SNSEvent.class,
                SNSEvent.SNS.class,
                SNSEvent.SNSRecord.class,
                SNSEvent.MessageAttribute.class,
                SQSBatchResponse.class,
                SQSBatchResponse.BatchItemFailure.class,
                SQSEvent.class,
                SQSEvent.SQSMessage.class,
                SQSEvent.MessageAttribute.class,
                StreamsEventResponse.class,
                StreamsEventResponse.BatchItemFailure.class,
                TimeWindow.class,
                TimeWindowEventResponse.class,
                TimeWindowEventResponse.BatchItemFailure.class,
        })
final class GraalVMHint {

    private GraalVMHint() {}
}
